server:
  port: 8080
spring:
  config:
    import: secrets.properties
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://root:root@localhost:27017/wallet?authSource=admin}
      database: wallet
      auto-index-creation: true